In [1]:
import numpy as np 
import pandas as pd

In [2]:
import sys

sys.path.append("/Users/sharaf/github/data_visualization/")
import os

os.getcwd()
DATA_DIRECTIORY_PATH = "/Users/sharaf/github/data_visualization/data/"
MORTICID_COLUMN_NAMES = [
    "country",
    "admin1",
    "subdiv",
    "year",
    "list",
    "cause",
    "sex",
    "format",
    "im_format",
    "death_all_agges",
    "death_range_0_year",
    "death_range_1_year",
    "death_range_2_year",
    "death_range_3_year",
    "death_range_4_year",
    "death_range_5_9",
    "death_range_10_14",
    "death_range_15_19",
    "death_range_20_24",
    "death_range_25_29",
    "death_range_30_34",
    "death_range_35_39",
    "death_range_40_44",
    "death_range_45_49",
    "death_range_50_54",
    "death_range_55_59",
    "death_range_60_64",
    "death_range_65_69",
    "death_range_70_74",
    "death_range_75_79",
    "death_range_80_84",
    "death_range_85_89",
    "death_range_90_94",
    "death_range_95_plus",
    "death_age_unspecficied",
    "infant_death_0_day",
    "infant_death_1_6_day",
    "infant_death_7_27_day",
    "infant_death_28_364_day",
]

In [3]:
df_country_codes = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/country_codes.csv")
df_country_codes["name"].nunique()
# 227 unique countries

227

In [4]:
df_morticid_pt1 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part1.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt2 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part2.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt3 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part3.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt4 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part4.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt5 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part5.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt6 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part6.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid= pd.concat([df_morticid_pt1,df_morticid_pt2,df_morticid_pt3,df_morticid_pt4,df_morticid_pt5,df_morticid_pt6])
df_morticid.head()
# 5,143,931 entries
# Year from 1988-2023
# 227

/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_60280/3551389357.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt1 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part1.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_60280/3551389357.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt2 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part2.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_60280/3551389357.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt3 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part3.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_60280/3551389357.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt4 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part4.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_60280/3551389357.py:5: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt5 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part5.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_60280/3551389357.py:6: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt6 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part6.csv",header=0, names=MORTICID_COLUMN_NAMES)

,country,admin1,subdiv,year,list,cause,sex,format,im_format,death_all_agges,...,death_range_75_79,death_range_80_84,death_range_85_89,death_range_90_94,death_range_95_plus,death_age_unspecficied,infant_death_0_day,infant_death_1_6_day,infant_death_7_27_day,infant_death_28_364_day
0,1400,NaN,NaN,2001,101,1000,1,7,8,332,...,95.0,NaN,NaN,NaN,NaN,0.0,8.0,NaN,NaN,NaN
1,1400,NaN,NaN,2001,101,1000,2,7,8,222,...,112.0,NaN,NaN,NaN,NaN,0.0,11.0,NaN,NaN,NaN
2,1400,NaN,NaN,2001,101,1001,1,7,8,24,...,5.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
3,1400,NaN,NaN,2001,101,1001,2,7,8,14,...,6.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
4,1400,NaN,NaN,2001,101,1002,1,7,8,0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN

In [5]:
df_morticid.head()

,country,admin1,subdiv,year,list,cause,sex,format,im_format,death_all_agges,...,death_range_75_79,death_range_80_84,death_range_85_89,death_range_90_94,death_range_95_plus,death_age_unspecficied,infant_death_0_day,infant_death_1_6_day,infant_death_7_27_day,infant_death_28_364_day
0,1400,NaN,NaN,2001,101,1000,1,7,8,332,...,95.0,NaN,NaN,NaN,NaN,0.0,8.0,NaN,NaN,NaN
1,1400,NaN,NaN,2001,101,1000,2,7,8,222,...,112.0,NaN,NaN,NaN,NaN,0.0,11.0,NaN,NaN,NaN
2,1400,NaN,NaN,2001,101,1001,1,7,8,24,...,5.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
3,1400,NaN,NaN,2001,101,1001,2,7,8,14,...,6.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
4,1400,NaN,NaN,2001,101,1002,1,7,8,0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN

In [6]:
df_cause_of_death_code = pd.read_csv(
    f"{DATA_DIRECTIORY_PATH}morticid/causes_of_death.csv",
    header=0,
    dtype={0: "int64", 1: "str", 2: "str"},
)
df_cause_of_death_code["Detailed List Numbers"] = pd.Series(df_cause_of_death_code["Detailed List Numbers"], dtype="string")
df_cause_of_death_code.head()

,code,Detailed List Numbers,Cause
0,1000,<NA>,All causes
1,1001,A00-B99,Certain infectious and parasitic diseases
2,1002,A00,Cholera
3,1003,A09,Diarrhoea and gastroenteritis of presumed infe...
4,1004,A01-A08,Other intestinal infectious diseases

In [26]:
def _get_alphabet_inbetween_two_letters(start_letter, end_letter):
    return list(map(chr, range(ord(start_letter)+1, ord(end_letter))))

In [37]:
def _get_letter_and_number(code):
    start_letter = code[0]
    start_number = code[1:]
    return start_letter, int(start_number)

In [57]:
def _handle_code_with_dash(detail_code, code_disease_dict, cause):
    dash_separated = detail_code.split("-")
    start_code = dash_separated[0].strip()
    end_code = dash_separated[1].strip()
    start_letter, start_number = _get_letter_and_number(start_code)
    end_letter, end_number = _get_letter_and_number(end_code)
    if not (start_letter == end_letter):
        letters_list = _get_alphabet_inbetween_two_letters(start_letter, end_letter)
        # Handle start letter letter plus first number till 99
        for i in range(int(start_number), 100):
            code_number = i 
            if code_number <10:
                code_number = f"0{code_number}"
            new_code = f"{start_letter}{code_number}"
            code_disease_dict[new_code] = cause
        # Handle in between letters
        for letter in letters_list:
            for i in range(0,100):
                code_number = i 
                if code_number <10:
                    code_number = f"0{code_number}"
                new_code = f"{letter}{code_number}"
                code_disease_dict[new_code] = cause
        # Handle end letter 
        for i in range(0, int(end_number)+1):
            code_number = i 
            if code_number <10:
                code_number = f"0{code_number}"
            new_code = f"{end_letter}{code_number}"
            code_disease_dict[new_code] = cause
             
    if start_letter == end_letter:
        for i in range(int(start_number), int(end_number) + 1):
            code_number = i 
            if code_number <10:
                code_number = f"0{code_number}"
            new_code = f"{start_letter}{code_number}"
            code_disease_dict[new_code] = cause
            # print(f'adding {new_code}:{cause}')

In [48]:
def _handle_single_code(detail_code, code_disease_dict, cause):
    detail_code = detail_code.strip()
    if len(detail_code) == 3:
        code_disease_dict[detail_code] = cause
        # print(f'adding {detail_code}:{cause}')
    else:
        print(f"error single code has more than 3 letters {detail_code}")

In [ ]:
code_disease_dict = {}

for _, row in df_cause_of_death_code.iterrows():
    detailed_code_full = row["Detailed List Numbers"]
    cause = row["Cause"]
    # print(detailed_code_full)
    if not pd.isna(detailed_code_full):
        # Hanlde comma separated codes
        if "," in detailed_code_full:
            comma_separated = detailed_code_full.split(",")
            for detail_code in comma_separated:
                if "-" in detail_code:
                    _handle_code_with_dash(detail_code, code_disease_dict, cause)
                else:
                    _handle_single_code(detail_code, code_disease_dict, cause)
        # handle - separated codes
        elif  "-" in detailed_code_full:
                _handle_code_with_dash(detailed_code_full, code_disease_dict, cause)
        # handle single codes
        else: 
            _handle_single_code(detailed_code_full, code_disease_dict, cause)
for key, value in code_disease_dict.items():
    print(key,value)
    df_cause_of_death_code = pd.concat([df_cause_of_death_code, pd.DataFrame([[key, None, value]], columns=df_cause_of_death_code.columns)], ignore_index=True)

A00 Cholera
A01 Other intestinal infectious diseases
A02 Other intestinal infectious diseases
A03 Other intestinal infectious diseases
A04 Other intestinal infectious diseases
A05 Other intestinal infectious diseases
A06 Other intestinal infectious diseases
A07 Other intestinal infectious diseases
A08 Other intestinal infectious diseases
A09 Diarrhoea and gastroenteritis of presumed infectious origin
A10 Certain infectious and parasitic diseases
A11 Certain infectious and parasitic diseases
A12 Certain infectious and parasitic diseases
A13 Certain infectious and parasitic diseases
A14 Certain infectious and parasitic diseases
A15 Respiratory tuberculosis
A16 Respiratory tuberculosis
A17 Other tuberculosis
A18 Other tuberculosis
A19 Other tuberculosis
A20 Plague
A21 Remainder of certain infectious and parasitic diseases
A22 Remainder of certain infectious and parasitic diseases
A23 Remainder of certain infectious and parasitic diseases
A24 Remainder of certain infectious and parasitic diseases
A25 Remainder of certain infectious and parasitic diseases
A26 Remainder of certain infectious and parasitic diseases
A27 Remainder of certain infectious and parasitic diseases
A28 Remainder of certain infectious and parasitic diseases
A29 Remainder of certain infectious and parasitic diseases
A30 Remainder of certain infectious and parasitic diseases
A31 Remainder of certain infectious and parasitic diseases
A32 Remainder of certain infectious and parasitic diseases
A33 Tetanus
A34 Tetanus
A35 Tetanus
A36 Diphtheria
A37 Whooping cough
A38 Remainder of certain infectious and parasitic diseases
A39 Meningococcal infection
A40 Septicaemia
A41 Septicaemia
A42 Remainder of certain infectious and parasitic diseases
A43 Remainder of certain infectious and parasitic diseases
A44 Remainder of certain infectious and parasitic diseases
A45 Remainder of certain infectious and parasitic diseases
A46 Remainder of certain infectious and parasitic diseases
A47 Remainder of certain infectious and parasitic diseases
A48 Remainder of certain infectious and parasitic diseases
A49 Remainder of certain infectious and parasitic diseases
A50 Infections with a predominantly sexual mode of transmission
A51 Infections with a predominantly sexual mode of transmission
A52 Infections with a predominantly sexual mode of transmission
A53 Infections with a predominantly sexual mode of transmission
A54 Infections with a predominantly sexual mode of transmission
A55 Infections with a predominantly sexual mode of transmission
A56 Infections with a predominantly sexual mode of transmission
A57 Infections with a predominantly sexual mode of transmission
A58 Infections with a predominantly sexual mode of transmission
A59 Infections with a predominantly sexual mode of transmission
A60 Infections with a predominantly sexual mode of transmission
A61 Infections with a predominantly sexual mode of transmission
A62 Infections with a predominantly sexual mode of transmission
A63 Infections with a predominantly sexual mode of transmission
A64 Infections with a predominantly sexual mode of transmission
A65 Remainder of certain infectious and parasitic diseases
A66 Remainder of certain infectious and parasitic diseases
A67 Remainder of certain infectious and parasitic diseases
A68 Remainder of certain infectious and parasitic diseases
A69 Remainder of certain infectious and parasitic diseases
A70 Remainder of certain infectious and parasitic diseases
A71 Remainder of certain infectious and parasitic diseases
A72 Remainder of certain infectious and parasitic diseases
A73 Remainder of certain infectious and parasitic diseases
A74 Remainder of certain infectious and parasitic diseases
A75 Remainder of certain infectious and parasitic diseases
A76 Remainder of certain infectious and parasitic diseases
A77 Remainder of certain infectious and parasitic diseases
A78 Remainder of certain infectious and parasitic diseases
A79 Remainder of certain infectious and parasitic diseases
A80 Acute poliomyelitis
A81 Remainder of certain infectious and parasitic diseases
A82 Rabies
A83 Remainder of certain infectious and parasitic diseases
A84 Remainder of certain infectious and parasitic diseases
A85 Remainder of certain infectious and parasitic diseases
A86 Remainder of certain infectious and parasitic diseases
A87 Remainder of certain infectious and parasitic diseases
A88 Remainder of certain infectious and parasitic diseases
A89 Remainder of certain infectious and parasitic diseases
A90 Other arthropod-borne viral fevers and viral haemorrhagic fevers
A91 Other arthropod-borne viral fevers and viral haemorrhagic fevers
A92 Other arthropod-borne viral fevers and viral haemorrhagic fevers
A93 Other arthropod-borne viral fevers and viral haemorrhagic fevers
A94 Other arthropod-borne viral fevers and viral haemorrhagic fevers
A95 Yellow fever
A96 Other arthropod-borne viral fevers and viral haemorrhagic fevers
A97 Other arthropod-borne viral fevers and viral haemorrhagic fevers
A98 Other arthropod-borne viral fevers and viral haemorrhagic fevers
A99 Other arthropod-borne viral fevers and viral haemorrhagic fevers
B00 Remainder of certain infectious and parasitic diseases
B01 Remainder of certain infectious and parasitic diseases
B02 Remainder of certain infectious and parasitic diseases
B03 Remainder of certain infectious and parasitic diseases
B04 Remainder of certain infectious and parasitic diseases
B05 Measles
B06 Remainder of certain infectious and parasitic diseases
B07 Remainder of certain infectious and parasitic diseases
B08 Remainder of certain infectious and parasitic diseases
B09 Remainder of certain infectious and parasitic diseases
B10 Certain infectious and parasitic diseases
B11 Certain infectious and parasitic diseases
B12 Certain infectious and parasitic diseases
B13 Certain infectious and parasitic diseases
B14 Certain infectious and parasitic diseases
B15 Viral hepatitis
B16 Viral hepatitis
B17 Viral hepatitis
B18 Viral hepatitis
B19 Viral hepatitis
B20 Human immunodeficiency virus [HIV] disease
B21 Human immunodeficiency virus [HIV] disease
B22 Human immunodeficiency virus [HIV] disease
B23 Human immunodeficiency virus [HIV] disease
B24 Human immunodeficiency virus [HIV] disease
B25 Remainder of certain infectious and parasitic diseases
B26 Remainder of certain infectious and parasitic diseases
B27 Remainder of certain infectious and parasitic diseases
B28 Remainder of certain infectious and parasitic diseases
B29 Remainder of certain infectious and parasitic diseases
B30 Remainder of certain infectious and parasitic diseases
B31 Remainder of certain infectious and parasitic diseases
B32 Remainder of certain infectious and parasitic diseases
B33 Remainder of certain infectious and parasitic diseases
B34 Remainder of certain infectious and parasitic diseases
B35 Remainder of certain infectious and parasitic diseases
B36 Remainder of certain infectious and parasitic diseases
B37 Remainder of certain infectious and parasitic diseases
B38 Remainder of certain infectious and parasitic diseases
B39 Remainder of certain infectious and parasitic diseases
B40 Remainder of certain infectious and parasitic diseases
B41 Remainder of certain infectious and parasitic diseases
B42 Remainder of certain infectious and parasitic diseases
B43 Remainder of certain infectious and parasitic diseases
B44 Remainder of certain infectious and parasitic diseases
B45 Remainder of certain infectious and parasitic diseases
B46 Remainder of certain infectious and parasitic diseases
B47 Remainder of certain infectious and parasitic diseases
B48 Remainder of certain infectious and parasitic diseases
B49 Remainder of certain infectious and parasitic diseases
B50 Malaria
B51 Malaria
B52 Malaria
B53 Malaria
B54 Malaria
B55 Leishmaniasis
B56 Trypanosomiasis
B57 Trypanosomiasis
B58 Remainder of certain infectious and parasitic diseases
B59 Remainder of certain infectious and parasitic diseases
B60 Remainder of certain infectious and parasitic diseases
B61 Remainder of certain infectious and parasitic diseases
B62 Remainder of certain infectious and parasitic diseases
B63 Remainder of certain infectious and parasitic diseases
B64 Remainder of certain infectious and parasitic diseases
B65 Schistosomiasis
B66 Remainder of certain infectious and parasitic diseases
B67 Remainder of certain infectious and parasitic diseases
B68 Remainder of certain infectious and parasitic diseases
B69 Remainder of certain infectious and parasitic diseases
B70 Remainder of certain infectious and parasitic diseases
B71 Remainder of certain infectious and parasitic diseases
B72 Remainder of certain infectious and parasitic diseases
B73 Remainder of certain infectious and parasitic diseases
B74 Remainder of certain infectious and parasitic diseases
B75 Remainder of certain infectious and parasitic diseases
B76 Remainder of certain infectious and parasitic diseases
B77 Remainder of certain infectious and parasitic diseases
B78 Remainder of certain infectious and parasitic diseases
B79 Remainder of certain infectious and parasitic diseases
B80 Remainder of certain infectious and parasitic diseases
B81 Remainder of certain infectious and parasitic diseases
B82 Remainder of certain infectious and parasitic diseases
B83 Remainder of certain infectious and parasitic diseases
B84 Remainder of certain infectious and parasitic diseases
B85 Remainder of certain infectious and parasitic diseases
B86 Remainder of certain infectious and parasitic diseases
B87 Remainder of certain infectious and parasitic diseases
B88 Remainder of certain infectious and parasitic diseases
B89 Remainder of certain infectious and parasitic diseases
B90 Remainder of certain infectious and parasitic diseases
B91 Remainder of certain infectious and parasitic diseases
B92 Remainder of certain infectious and parasitic diseases
B93 Remainder of certain infectious and parasitic diseases
B94 Remainder of certain infectious and parasitic diseases
B95 Certain infectious and parasitic diseases
B96 Certain infectious and parasitic diseases
B97 Certain infectious and parasitic diseases
B98 Certain infectious and parasitic diseases
B99 Remainder of certain infectious and parasitic diseases
C00 Malignant neoplasm of lip, oral cavity and pharynx
C01 Malignant neoplasm of lip, oral cavity and pharynx
C02 Malignant neoplasm of lip, oral cavity and pharynx
C03 Malignant neoplasm of lip, oral cavity and pharynx
C04 Malignant neoplasm of lip, oral cavity and pharynx
C05 Malignant neoplasm of lip, oral cavity and pharynx
C06 Malignant neoplasm of lip, oral cavity and pharynx
C07 Malignant neoplasm of lip, oral cavity and pharynx
C08 Malignant neoplasm of lip, oral cavity and pharynx
C09 Malignant neoplasm of lip, oral cavity and pharynx
C10 Malignant neoplasm of lip, oral cavity and pharynx
C11 Malignant neoplasm of lip, oral cavity and pharynx
C12 Malignant neoplasm of lip, oral cavity and pharynx
C13 Malignant neoplasm of lip, oral cavity and pharynx
C14 Malignant neoplasm of lip, oral cavity and pharynx
C15 Malignant neoplasm of oesophagus
C16 Malignant neoplasm of stomach
C17 Remainder of malignant neoplasms
C18 Malignant neoplasm of colon, rectum and anus
C19 Malignant neoplasm of colon, rectum and anus
C20 Malignant neoplasm of colon, rectum and anus
C21 Malignant neoplasm of colon, rectum and anus
C22 Malignant neoplasm of liver and intrahepatic bile ducts
C23 Remainder of malignant neoplasms
C24 Remainder of malignant neoplasms
C25 Malignant neoplasm of pancreas
C26 Remainder of malignant neoplasms
C27 Remainder of malignant neoplasms
C28 Remainder of malignant neoplasms
C29 Remainder of malignant neoplasms
C30 Remainder of malignant neoplasms
C31 Remainder of malignant neoplasms
C32 Malignant neoplasm of larynx
C33 Malignant neoplasm of trachea, bronchus and lung
C34 Malignant neoplasm of trachea, bronchus and lung
C35 Neoplasms
C36 Neoplasms
C37 Remainder of malignant neoplasms
C38 Remainder of malignant neoplasms
C39 Remainder of malignant neoplasms
C40 Remainder of malignant neoplasms
C41 Remainder of malignant neoplasms
C42 Neoplasms
C43 Malignant melanoma of skin
C44 Remainder of malignant neoplasms
C45 Remainder of malignant neoplasms
C46 Remainder of malignant neoplasms
C47 Remainder of malignant neoplasms
C48 Remainder of malignant neoplasms
C49 Remainder of malignant neoplasms
C50 Malignant neoplasm of breast
C51 Remainder of malignant neoplasms
C52 Remainder of malignant neoplasms
C53 Malignant neoplasm of cervix uteri
C54 Malignant neoplasm of other and unspecified parts of uterus
C55 Malignant neoplasm of other and unspecified parts of uterus
C56 Malignant neoplasm of ovary
C57 Remainder of malignant neoplasms
C58 Remainder of malignant neoplasms
C59 Remainder of malignant neoplasms
C60 Remainder of malignant neoplasms
C61 Malignant neoplasm of prostate
C62 Remainder of malignant neoplasms
C63 Remainder of malignant neoplasms
C64 Remainder of malignant neoplasms
C65 Remainder of malignant neoplasms
C66 Remainder of malignant neoplasms
C67 Malignant neoplasm of bladder
C68 Remainder of malignant neoplasms
C69 Remainder of malignant neoplasms
C70 Malignant neoplasm of meninges, brain and other parts of central nervous system
C71 Malignant neoplasm of meninges, brain and other parts of central nervous system
C72 Malignant neoplasm of meninges, brain and other parts of central nervous system
C73 Remainder of malignant neoplasms
C74 Remainder of malignant neoplasms
C75 Remainder of malignant neoplasms
C76 Remainder of malignant neoplasms
C77 Remainder of malignant neoplasms
C78 Remainder of malignant neoplasms
C79 Remainder of malignant neoplasms
C80 Remainder of malignant neoplasms
C81 Remainder of malignant neoplasms
C82 Non-Hodgkin's lymphoma
C83 Non-Hodgkin's lymphoma
C84 Non-Hodgkin's lymphoma
C85 Non-Hodgkin's lymphoma
C86 Neoplasms
C87 Neoplasms
C88 Remainder of malignant neoplasms
C89 Neoplasms
C90 Multiple myeloma and malignant plasma cell neoplasms
C91 Leukaemia
C92 Leukaemia
C93 Leukaemia
C94 Leukaemia
C95 Leukaemia
C96 Remainder of malignant neoplasms
C97 Remainder of malignant neoplasms
C98 Neoplasms
C99 Neoplasms
D00 Remainder of neoplasms
D01 Remainder of neoplasms
D02 Remainder of neoplasms
D03 Remainder of neoplasms
D04 Remainder of neoplasms
D05 Remainder of neoplasms
D06 Remainder of neoplasms
D07 Remainder of neoplasms
D08 Remainder of neoplasms
D09 Remainder of neoplasms
D10 Remainder of neoplasms
D11 Remainder of neoplasms
D12 Remainder of neoplasms
D13 Remainder of neoplasms
D14 Remainder of neoplasms
D15 Remainder of neoplasms
D16 Remainder of neoplasms
D17 Remainder of neoplasms
D18 Remainder of neoplasms
D19 Remainder of neoplasms
D20 Remainder of neoplasms
D21 Remainder of neoplasms
D22 Remainder of neoplasms
D23 Remainder of neoplasms
D24 Remainder of neoplasms
D25 Remainder of neoplasms
D26 Remainder of neoplasms
D27 Remainder of neoplasms
D28 Remainder of neoplasms
D29 Remainder of neoplasms
D30 Remainder of neoplasms
D31 Remainder of neoplasms
D32 Remainder of neoplasms
D33 Remainder of neoplasms
D34 Remainder of neoplasms
D35 Remainder of neoplasms
D36 Remainder of neoplasms
D37 Remainder of neoplasms
D38 Remainder of neoplasms
D39 Remainder of neoplasms
D40 Remainder of neoplasms
D41 Remainder of neoplasms
D42 Remainder of neoplasms
D43 Remainder of neoplasms
D44 Remainder of neoplasms
D45 Remainder of neoplasms
D46 Remainder of neoplasms
D47 Remainder of neoplasms
D48 Remainder of neoplasms
D50 Anaemias
D51 Anaemias
D52 Anaemias
D53 Anaemias
D54 Anaemias
D55 Anaemias
D56 Anaemias
D57 Anaemias
D58 Anaemias
D59 Anaemias
D60 Anaemias
D61 Anaemias
D62 Anaemias
D63 Anaemias
D64 Anaemias
D65 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D66 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D67 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D68 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D69 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D70 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D71 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D72 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D73 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D74 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D75 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D76 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D77 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D78 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D79 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D80 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D81 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D82 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D83 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D84 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D85 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D86 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D87 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D88 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
D89 Remainder of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
E00 Remainder of endocrine, nutritional and metabolic diseases
E01 Remainder of endocrine, nutritional and metabolic diseases
E02 Remainder of endocrine, nutritional and metabolic diseases
E03 Remainder of endocrine, nutritional and metabolic diseases
E04 Remainder of endocrine, nutritional and metabolic diseases
E05 Remainder of endocrine, nutritional and metabolic diseases
E06 Remainder of endocrine, nutritional and metabolic diseases
E07 Remainder of endocrine, nutritional and metabolic diseases
E08 Endocrine, nutritional and metabolic diseases
E09 Endocrine, nutritional and metabolic diseases
E10 Diabetes mellitus
E11 Diabetes mellitus
E12 Diabetes mellitus
E13 Diabetes mellitus
E14 Diabetes mellitus
E15 Remainder of endocrine, nutritional and metabolic diseases
E16 Remainder of endocrine, nutritional and metabolic diseases
E17 Remainder of endocrine, nutritional and metabolic diseases
E18 Remainder of endocrine, nutritional and metabolic diseases
E19 Remainder of endocrine, nutritional and metabolic diseases
E20 Remainder of endocrine, nutritional and metabolic diseases
E21 Remainder of endocrine, nutritional and metabolic diseases
E22 Remainder of endocrine, nutritional and metabolic diseases
E23 Remainder of endocrine, nutritional and metabolic diseases
E24 Remainder of endocrine, nutritional and metabolic diseases
E25 Remainder of endocrine, nutritional and metabolic diseases

In [ ]:
df_morticid.head(10)
df_country_codes.head(10)
df_morticid_merged = pd.merge(
    df_morticid,
    df_country_codes,
    on="country",
).drop(["admin1", "subdiv", "format",
    "im_format", "list", "death_range_20_24",
    "death_range_25_29",
    "death_range_30_34",
    "death_range_35_39",
    "death_range_40_44",
    "death_range_45_49",
    "death_range_50_54",
    "death_range_55_59",
    "death_range_60_64",
    "death_range_65_69",
    "death_range_70_74",
    "death_range_75_79",
    "death_range_80_84",
    "death_range_85_89",
    "death_range_90_94",
    "death_range_95_plus",
    "death_age_unspecficied",
    "infant_death_0_day",
    "infant_death_1_6_day",
    "infant_death_7_27_day",
        "death_all_agges",
    "infant_death_28_364_day",], axis=1)
df_morticid_merged["cause"] = pd.Series(df_morticid_merged["cause"], dtype="string")
df_morticid_merged["cause"].value_counts()

cause
AAA     5529
I64     5118
R99     5095
I10     4938
G20     4579
        ...
L946       1
X853       1
X281       1
Q685       1
L293       1
Name: count, Length: 11555, dtype: Int64

In [ ]:
# df_morticid_merged = pd.merge(
#     left=df_morticid_merged,
#     right=df_cause_of_death_code,
#     left_on="cause",
#     right_on="code"
# )
# df_morticid_merged.head()

ValueError: You are trying to merge on object and int64 columns for key 'cause'. If you wish to proceed you should use pd.concat